#[derive(Debug, Clone)]
pub enum Code {
    Constant(usize),
    Echo,
    Add,
    Subtract,
    Multiply,
    Divide,
    Concat,
    LessThan,
    GreaterThan,
    Assign(String),
    Get(String),
    GetConstant(String),
    Jump(usize),
    JumpIfFalse(usize),
    JumpIfTrue(usize),
    Pop,
    True,
    False,
    Return,
    ReturnWith,
    InitCall(String),
    DoUserCall,
    DoInternalCall,
    SendArg,
}